- name: dpkg unlock
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - /var/lib/dpkg/lock
  - /var/lib/dpkg/lock-frontend
  ignore_errors: yes


- name: Add gitlab ppa repository
  ansible.builtin.shell: |
    curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | bash

- name: Add git apt key by id from a keyserver
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: A1715D88E1DF1F24
    state: present
  become: yes

- name: Install Dependency
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - ca-certificates
    - tzdata
    - perl

- name: Install Gitlab-CE
  package:
    name: gitlab-ce
    state: present

- name: Create Gitlab Cert Directory
  ansible.builtin.file:
    path: "{{ gitlab_ssl_path }}"
    state: directory
    mode: '0755'
    recurse: yes
    owner: root
    group: root

- name: Copy fullchain
  ansible.builtin.copy:
    src: files/certs/fullchain1.pem
    dest: /etc/gitlab/ssl/{{ gitlab_domain }}.crt

- name: Copy privkey
  ansible.builtin.copy:
    src: files/certs/privkey1.pem
    dest: /etc/gitlab/ssl/{{ gitlab_domain }}.key

- name: config gitlab.rb
  ansible.builtin.template:
    src: "{{ gitlab_config }}"
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: 0644

- name: gitlab-ctl reconfigure
  command: gitlab-ctl reconfigure
