- name: Create Sonarqube Data mount directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
  - /data/sonarqube/data
  - /data/sonarqube/extensions
  - /data/sonarqube/logs

- name: Install Sonarqube
  ansible.builtin.shell: |
    docker run -d --name sonarqube -p {{ sonarqube_port }}:9000  \
      -e SONAR_JDBC_URL=jdbc:postgresql://172.17.0.1/sonar \
      -e SONAR_JDBC_USERNAME=sonar \
      -e SONAR_JDBC_PASSWORD=root \
      -v /data/sonarqube/data:/opt/sonarqube/data \
      -v /data/sonarqube/extensions:/opt/sonarqube/extensions \
      -v /data/sonarqube/logs:/opt/sonarqube/logs \
      --add-host {{ gitlab_domain }}:{{ hostvars[ groups['haproxy'][0] ].ansible_host }} \
      --restart=always sonarqube:{{ sonarqube_version }}-community
