- name: Install Lab
  hosts: all
  become: true
  pre_tasks:
    - name: include env vars
      include_vars: vars/main.yml
  roles:
  - ./roles/haproxy
  - ./roles/rke2
  - ./roles/rancher
  - ./roles/argocd
  - ./roles/harbor
  - ./roles/gitlab
  - ./roles/gitlab-runner
  - ./roles/nexus
  - ./roles/sonarqube
