- name: Install Lab
  hosts: all
  become: true
  pre_tasks:
    - name: include env vars
      include_vars: vars/main.yml
  roles:
  - haproxy
  - rke2
  - rancher
  - argocd
  - harbor
  - gitlab
  - gitlab-runner
  - nexus
  - sonarqube
