---
rke2_servers_group_name: masters
rke2_cluster_group_name: k8s_cluster
rke2_first_master_config: templates/first_master_config.yaml.j2
rke2_ha_master_config: templates/ha_master_config.yaml.j2
rke2_api_ip: "{{ hostvars[groups[rke2_servers_group_name].0]['ansible_default_ipv4']['address'] }}"
rke2_cni: canal
rke2_token: testrke2token
rke2_version: v1.23.6+rke2r2
rke2_data_path: /var/lib/rancher/rke2
k9s_version: v0.25.18
cri_endpoint: /run/k3s/containerd/containerd.sock
