- name: Install Rke2
  shell: curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION={{ rke2_version }} sh -
  retries: 10
  delay: 3
  register: result
  until: result is not failed

- name: create rke2 directory
  file:
    path: /etc/rancher/rke2
    state: directory
    owner: root
    group: root

- name: Copy rke2 config
  ansible.builtin.template:
    src: "{{ rke2_ha_master_config }}"
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: 0644

- name: Start RKE2 service on the rest of the nodes
  ansible.builtin.systemd:
    name: "rke2-{{ rke2_type }}.service"
    state: started
    enabled: true
  retries: 10
  delay: 3
  register: result
  until: result is not failed
  environment:
    RKE2_TOKEN: "{{ rke2_token }}"

- name: create ~/.kube directory
  file:
    path: /root/.kube
    state: directory
    owner: root
    group: root

- name: copy kubeconfig
  copy:
    src: /etc/rancher/rke2/rke2.yaml
    dest: /root/.kube/config
    owner: root
    group: root
    remote_src: yes

- name: copy kubectl
  copy:
    src: /var/lib/rancher/rke2/bin/kubectl
    dest: /usr/bin/kubectl
    mode: 755

- name: import rke2/bin path into profile
  lineinfile:
    path: '/root/.profile'
    line: 'export PATH=$PATH:/var/lib/rancher/rke2/bin/'
    insertafter: EOF

- name: Wait for remaining nodes to be ready
  ansible.builtin.shell: |
   set -o pipefail
   {{ rke2_data_path }}/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml get nodes | grep " Ready" | wc -l
  args:
    executable: /bin/bash
  changed_when: false
  register: all_ready_nodes
  until:
    "groups[rke2_cluster_group_name] | length == all_ready_nodes.stdout | int"
  retries: 100
  delay: 15
  delegate_to: "{{ active_server | default(groups[rke2_servers_group_name].0) }}"
  run_once: true
