- name: Get k9s binary
  get_url:
    url: https://github.com/derailed/k9s/releases/download/{{ k9s_version }}/k9s_Linux_x86_64.tar.gz
    dest: /tmp/k9s.tar.gz
    mode: '0644'

- name: Extract k9s tarball
  ansible.builtin.unarchive:
    src: /tmp/k9s.tar.gz
    dest: /tmp/
    remote_src: yes
  retries: 10
  delay: 3
  register: result
  until: result is not failed

- name: Move k9s to bin
  command: mv /tmp/k9s /usr/local/bin
