---
# tasks file for role-rke2
- name: OS Setup
  ansible.builtin.include_tasks: os_setup.yml

- name: Activate first master
  ansible.builtin.include_tasks: first_master.yml
  when:
  - inventory_hostname == groups[rke2_servers_group_name].0

- name: Join remaining nodes
  ansible.builtin.include_tasks: ha_master.yml
  when:
  - inventory_hostname in groups[rke2_servers_group_name]
  - inventory_hostname != groups[rke2_servers_group_name].0

- name: Install k9s
  ansible.builtin.include_tasks: k9s.yml
  when:
  - inventory_hostname in groups[rke2_servers_group_name]
