- name: Disable swap
  command: swapoff -a

- name: dpkg unlock
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - /var/lib/dpkg/lock-frontend
  - /var/lib/dpkg/lock
  ignore_errors: yes

- name: Update apt packages
  become: true
  apt:
  #  upgrade: full
    update_cache: yes
  #  cache_valid_time: 86400 #One day

- name: ufw disable
  command: "{{ item }}"
  with_items:
  - systemctl stop ufw
  - ufw disable
  - iptables -F

- name: Install needed package
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
  - jq
  - docker.io
  retries: 10
  delay: 3
  register: result
  until: result is not failed
