- name: Download helm
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0700'

- name: Install helm
  script: /tmp/get_helm.sh

- name: Install Cert Manager
  ansible.builtin.shell: |
    {{ kubectl }} apply -f https://github.com/jetstack/cert-manager/releases/download/{{ cert_manager_version }}/cert-manager.yaml
    {{ kubectl }} get pod -n cert-manager -l app.kubernetes.io/instance=cert-manager -o jsonpath="{.items[*].status.conditions}" | jq
    {{ kubectl }} wait pods -n cert-manager -l app.kubernetes.io/instance=cert-manager --for condition=Ready --timeout=300s

- name: Wait for Cert Manager state in Ready
  command: sleep 30
