- name: acl config
  lineinfile:
    path: /etc/haproxy/haproxy.cfg
    line: acl harbor hdr_end(host) -i {{ harbor_domain }}
    insertbefore: '^acl'

- name: backend matching
  lineinfile:
    path: /etc/haproxy/haproxy.cfg
    line: use_backend harbor if harbor
    insertbefore: '^use_backend'

- name: backend config
  blockinfile:
    marker: "# {mark} Harbor Backend"
    block: "{{ lookup('template', 'config.yaml.j2') }}"
    dest: "/etc/haproxy/haproxy.cfg"
    insertafter: EOF

- name: Restart Haproxy service
  ansible.builtin.systemd:
    name: "haproxy.service"
    state: restarted
    enabled: true
