---
- name: Install Docker
  ansible.builtin.include_tasks: docker.yml

- name: hosts config
  ansible.builtin.include_tasks: hosts.yml

- name: Install Harbor
  ansible.builtin.include_tasks: harbor.yml
  when:
  - inventory_hostname in groups['harbor']
  - inventory_hostname not in groups['haproxy']

- name: config haproxy
  ansible.builtin.include_tasks: ha_config.yml
  when:
  - inventory_hostname in groups['haproxy']
